spring:
  application:
    name: K8SecretsDemo
enc:
  com:
    oup:
      cheekysecret: ENC(0qi1DdPSi1w+qllsbntF+koijt4uXa2CVKLe6betV4g3kuNLbTXVTtHVFyfv6ktW) 
      #ENC(Z+ELc+oIPOjfNzzR6vPGLOMz4smDnFO2rh25ZYSzT7mMceBM3AEQ9MvEbBaEId41)
jasypt:
  encryptor:
    password: ${JASYPT_SECRET_KEY}
    #${JASYPT_SECRET_KEY}